### PR TITLE
Update for base / core v0.16

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Minor fixes to support base/core v0.16, which I've validated on macOS and linux. 
Added some missing transitive dependencies that are not listed in opam files but are used in dune files.

### CODE REVIEW

**Comment by quernd** [comment]
Thanks! We had to do the same fix for `Time_unix` in our codebase.
I'm just a bit confused about the transitive dependencies. For instance, you added `h2` to `grpc-lwt`, but it depends on `grpc` which already depends on `h2`. Maybe I'm missing something but could you explain your reasoning here?

**Comment by tmcgilchrist** [comment]
@quernd I introduced an inconsistency with the dependencies for `grpc-async` when I originally added async support. Now this should be more inline with `grpc-lwt` such that it depends on h2 coming from the grpc package and you choose `h2-async` in the example code when you need to run things.

**Comment by tmcgilchrist** [comment]
Ping @quernd are you ok with these changes?

**Review by quernd — APPROVED** [review]
Sorry @tmcgilchrist I thought I had approved this one already 🥺

**Pull request merged**
